### ISSUE TITLE
您好，关于拦截事件我有点疑问

### ISSUE THREAD

**Issue by FiroKuo** [ckenergy/TextViewClickDemo#1]
您好，是这样的。我想实现变色部分父类不拦截事件，其他部分父类拦截事件，比如在RecyclerView的item中，我想点击非变色的部分父类仍然能响应事件，我写了如下代码，只是添加了一个else，但是父类却不能收到事件，为什么呢？另外，感谢你的博客。

ACTION_DOWN事件：
//变色
for (Section section : sections) {
                            if (index >= section.start && index <= section.end) {
                                Log.e(TAG, section.start + ":" + section.end);
                                //处理背景变色
                                spannableStringBuilder.setSpan(span, section.start, section.end, Spannable.SPAN_INCLUSIVE_INCLUSIVE);

                                downSection=section;
                                downX=(int)event.getX();
                                downY=(int)event.getY();
                                textView.setText(spannableStringBuilder);
                                textView.getParent().requestDisallowInterceptTouchEvent(true);//不允许父view拦截

                            }**else if (index>section.end){
                                return false;//我想要将事件交给父类**
                            }
                        }

**Comment by ckenergy** [comment]
好的，我先调试下

**Comment by ckenergy** [comment]
@swordsman-guo 你好，我发现了可能是这个错误。
把下面这个注释了，我试了点击非变色部分，RecyclerView的item是可以响应事件。
/\*if (matcher.find()) {
            if (!(textView instanceof EditText)) {
                textView.setMovementMethod(LinkMovementMethod.getInstance());
                textView.setFocusable(false);
                textView.setClickable(false);
                textView.setLongClickable(false);
            }
            matcher.reset();
        }\*/

        while (matcher.find()) { ....
新的内容我已经上传了，因为我有一个开源的微博项目也用了这个库，但是在那边却没有这个情况，所以一直都没有发现这个问题，感谢你的反馈！
如果还有什么问题，欢迎再给我反馈。

**Comment by FiroKuo** [comment]
问题解决了，感谢！
